FROM nginx:latest
LABEL org.opencontainers.image.source=https://github.com/CoEDL/nyingarn-workspace
LABEL org.opencontainers.image.description="The Nyingarn Repository UI container"
LABEL org.opencontainers.image.licenses=GPLv3

# RUN apt-get update && apt-get install -y nginx-extras
RUN rm /etc/nginx/conf.d/default.conf

COPY ./ui-repository/dist/ /srv/ui/

CMD ["nginx", "-g", "daemon off;"]