FROM node:18-bullseye-slim
LABEL org.opencontainers.image.source=https://github.com/CoEDL/nyingarn-workspace
LABEL org.opencontainers.image.description="The Nyingarn Workspace Tasks container"
LABEL org.opencontainers.image.licenses=GPLv3

RUN apt-get update && apt-get install -y  postgresql-client ca-certificates
COPY tasks /srv/tasks
COPY api /srv/api
WORKDIR /srv/tasks
RUN cd /src/tasks && npm install
RUN cd /src/api && npm install

CMD [ "node", "/srv/tasks/index.js" ]
