version: "3.7"

networks:
  default:
    external:
      name: workspace_default

volumes:
    api_node_modules:
        driver: local
    ui_node_modules:
        driver: local

services:
    tus:
        image: arkisto/workspace-tusd
        restart: always
        ports:
            - 1080:1080
        volumes:
            - /srv/workspace-data/tus:/data
        user: root
        environment:
            AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
            AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
            AWS_DEFAULT_REGION: "${AWS_DEFAULT_REGION}"
            S3_ENDPOINT_URL: "${S3_ENDPOINT_URL}"
            S3_BUCKET: "${S3_BUCKET}"
            API_ENDPOINT_URL: "${WORKSPACE_API_ENDPOINT_URL}"
        command: [
          "-verbose",
          "-hooks-dir", "/srv/tusd-hooks", 
          "-upload-dir", "/data", 
          "-behind-proxy", "true", "-expose-metrics", "false" ]
    workspace_api:
        image: arkisto/workspace-api:latest
        hostname: workspace-api
        tty: true
        environment:
            TERM: "xterm-256color"
            DB_HOST: "${POSTGRES_HOST}"
            DB_PORT: "${POSTGRES_PORT}"
            DB_USER: "${POSTGRES_USER}"
            DB_PASSWORD: "${POSTGRES_PASSWORD}"
            DB_DATABASE: "${NYINGARN_DB}"
        volumes:
            - ./configuration-nyingarn.json:/srv/configuration.json
    workspace-ui:
        image: arkisto/workspace-ui:latest
        hostname: workspace-ui
        tty: true
        environment:
            TERM: "xterm-256color"
            NODE_ENV: "development"
        volumes:
          - /srv/workspace/letsencrypt:/srv/letsencrypt
          - ./dhparams.pem:/etc/nginx/dhparams.pem
          - ./edge-nginx-tus.conf:/etc/nginx/conf.d/nginx-tus.conf
          - ./edge-nginx-workspace.conf:/etc/nginx/conf.d/nginx-workspace.conf
          - ./edge-nginx-s3.conf:/etc/nginx/conf.d/nginx-s3.conf
          - ./edge-nginx-s3-console.conf:/etc/nginx/conf.d/nginx-s3-console.conf
          - ./edge-nginx-describo.conf:/etc/nginx/conf.d/nginx-describo.conf
        ports:
            - 80:80
            - 443:443
