version: "3.7"

networks:
  default:
    external:
      name: workspace_default

volumes:
    database_volume:
        driver: local

services:
    describo_api:
        image: arkisto/describo-online-api:latest
        hostname: describo-api
        tty: true
        environment:
            TERM: "xterm-256color"
            DB_HOST: "${POSTGRES_HOST}"
            DB_PORT: "${POSTGRES_PORT}"
            DB_USER: "${POSTGRES_USER}"
            DB_PASSWORD: "${POSTGRES_PASSWORD}"
            DB_DATABASE: "${DESCRIBO_DB}"
        volumes:
            - ./configuration-describo.json:/srv/configuration.json
    describo_ui:
        image: arkisto/describo-online-ui:latest
        hostname: describo-ui
        tty: true
        environment:
            TERM: "xterm-256color"
        volumes:
            - ./internal-nginx-describo.conf:/etc/nginx/conf.d/default.conf
